#!/bin/bash

iojs getCtripPlaceList ./citys/EU/austria.json            ./eu/austria.json    
iojs getCtripPlaceList ./citys/EU/belarus.json            ./eu/belarus.json    
iojs getCtripPlaceList ./citys/EU/belgium.json            ./eu/belgium.json    
iojs getCtripPlaceList ./citys/EU/denmark.json            ./eu/denmark.json    
iojs getCtripPlaceList ./citys/EU/finland.json            ./eu/finland.json    
iojs getCtripPlaceList ./citys/EU/france.json             ./eu/france.json   
iojs getCtripPlaceList ./citys/EU/germany.json            ./eu/germany.json    
iojs getCtripPlaceList ./citys/EU/greece.json             ./eu/greece.json   
iojs getCtripPlaceList ./citys/EU/holland.json            ./eu/holland.json    
iojs getCtripPlaceList ./citys/EU/hungary.json            ./eu/hungary.json    
iojs getCtripPlaceList ./citys/EU/iceland.json            ./eu/iceland.json    
iojs getCtripPlaceList ./citys/EU/ireland.json            ./eu/ireland.json    
iojs getCtripPlaceList ./citys/EU/italy.json              ./eu/italy.json  
iojs getCtripPlaceList ./citys/EU/latvija.json            ./eu/latvija.json    
iojs getCtripPlaceList ./citys/EU/lithuania.json          ./eu/lithuania.json      
iojs getCtripPlaceList ./citys/EU/luxemburg.json          ./eu/luxemburg.json      
iojs getCtripPlaceList ./citys/EU/norway.json             ./eu/norway.json   
iojs getCtripPlaceList ./citys/EU/poland.json             ./eu/poland.json   
iojs getCtripPlaceList ./citys/EU/portugal.json           ./eu/portugal.json     
iojs getCtripPlaceList ./citys/EU/russia.json             ./eu/russia.json   
iojs getCtripPlaceList ./citys/EU/spain.json              ./eu/spain.json  
iojs getCtripPlaceList ./citys/EU/sweden.json             ./eu/sweden.json   
iojs getCtripPlaceList ./citys/EU/switzerland.json        ./eu/switzerland.json        
iojs getCtripPlaceList ./citys/EU/theczechrepublic.json   ./eu/theczechrepublic.json             
iojs getCtripPlaceList ./citys/EU/turkey.json             ./eu/turkey.json   
iojs getCtripPlaceList ./citys/EU/ukraine.json            ./eu/ukraine.json    
iojs getCtripPlaceList ./citys/EU/unitedkingdom.json      ./eu/unitedkingdom.json          
iojs getCtripPlaceList ./citys/EU/vatican.json            ./eu/vatican.json    